package com.mycompany.intergraphs.views;

import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class VistaPerfil extends javax.swing.JFrame {

    /**
     * Creates new form VistaPerfil
     */
    public VistaPerfil() {
        initComponents();
        // Cargar imagen de perfil por defecto
        ImageIcon userIcon = new ImageIcon(getClass().getResource("/user.png"));
        jLabelUserImage.setIcon(new ImageIcon(userIcon.getImage().getScaledInstance(jLabelUserImage.getWidth(), jLabelUserImage.getHeight(), java.awt.Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelGames = new javax.swing.JLabel();
        jLabelWins = new javax.swing.JLabel();
        jLabelLosses = new javax.swing.JLabel();
        jLabelUsernameValue = new javax.swing.JLabel();
        jLabelGamesValue = new javax.swing.JLabel();
        jLabelWinsValue = new javax.swing.JLabel();
        jLabelLossesValue = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonSelectImage = new javax.swing.JButton();
        jLabelUserImage = new javax.swing.JLabel();
        jLabelAvatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));
        setPreferredSize(new java.awt.Dimension(850, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsername.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Nombre de usuario:");
        getContentPane().add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 300, 40));

        jLabelUsernameValue.setFont(new java.awt.Font("Tw Cen MT", 0, 30)); // NOI18N
        jLabelUsernameValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsernameValue.setText("User1");  // Aquí deberías cargar el valor desde la base de datos
        getContentPane().add(jLabelUsernameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 300, 40));

        jLabelGames.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabelGames.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGames.setText("Juegos:");
        getContentPane().add(jLabelGames, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, 40));

        jLabelGamesValue.setFont(new java.awt.Font("Tw Cen MT", 0, 30)); // NOI18N
        jLabelGamesValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGamesValue.setText("10");  // Aquí deberías cargar el valor desde la base de datos
        getContentPane().add(jLabelGamesValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, 40));

        jLabelWins.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabelWins.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWins.setText("Victorias:");
        getContentPane().add(jLabelWins, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, 40));

        jLabelWinsValue.setFont(new java.awt.Font("Tw Cen MT", 0, 30)); // NOI18N
        jLabelWinsValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWinsValue.setText("7");  // Aquí deberías cargar el valor desde la base de datos
        getContentPane().add(jLabelWinsValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 150, 40));

        jLabelLosses.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabelLosses.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLosses.setText("Derrotas:");
        getContentPane().add(jLabelLosses, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 150, 40));

        jLabelLossesValue.setFont(new java.awt.Font("Tw Cen MT", 0, 30)); // NOI18N
        jLabelLossesValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLossesValue.setText("3");  // Aquí deberías cargar el valor desde la base de datos
        getContentPane().add(jLabelLossesValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 150, 40));

        jButtonSave.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButtonSave.setText("Guardar");
        getContentPane().add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 150, 40));

        jButtonSelectImage.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButtonSelectImage.setText("Seleccionar Icono");
        getContentPane().add(jButtonSelectImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 250, 40));

        jLabelUserImage.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabelUserImage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserImage.setText("User Image");
        getContentPane().add(jLabelUserImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 150, 150));

        jLabelAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.png"))); // NOI18N
        getContentPane().add(jLabelAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSelectImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAvatar;
    private javax.swing.JLabel jLabelLosses;
    private javax.swing.JLabel jLabelGames;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelWins;
    private javax.swing.JLabel jLabelUserImage;
    private javax.swing.JLabel jLabelLossesValue;
    private javax.swing.JLabel jLabelGamesValue;
    private javax.swing.JLabel jLabelUsernameValue;
    private javax.swing.JLabel jLabelWinsValue;
    // End of variables declaration//GEN-END:variables
}
